
@echo off

REM !!! Generated by the fmp-cli 1.70.0.  DO NOT EDIT!

md Hotspot3D\Assets\3rd\fmp-xtc-hotspot3d

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-hotspot3d-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\Hotspot3D\Assets\3rd\fmp-xtc-hotspot3d\
